# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master, 1.2.x ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x bin/gradlew
    - name: Build with Gradle
      run: ./bin/gradlew check
    - name: Upload Jacoco Report
      run: bash <(curl -s https://codecov.io/bash)
